
---
- name: Configure Routing and Gateways
  hosts: all
  tasks:
    - name: Enable IP Forwarding on Router (Scenario 02)
      shell: echo 1 > /proc/sys/net/ipv4/ip_forward
      when: inventory_hostname == 'router1'

    - name: Set Default Gateway for LAN 1
      shell: ip route add default via 192.168.10.1 || true
      when: inventory_hostname in ['host1', 'host2']

    - name: Set Default Gateway for LAN 2
      shell: ip route add default via 192.168.10.33 || true
      when: inventory_hostname in ['host3', 'host4']
